### ISSUE TITLE
[ENHANCMENT] Auto-place selected card to suit stack

### ISSUE THREAD

**Issue by HurleybirdJr** [spsandwichman/consolitaire#1]
## Description
Add a feature that auto-places the current selected card into the next
free slot in the suit stack ( if ace `♠` ) then remaining suit cards can follow after.

## Concept Diagram
[![HIGHLIGHTED IN - GREEN](https://img.shields.io/badge/HIGHLIGHTED_IN-GREEN-00C600?style=for-the-badge)](https://)

![image](https://user-images.githubusercontent.com/45840763/236644521-6e6cf159-f2d4-448f-be1f-93456648a9f3.png)

**Comment by spsandwichman** [comment]
should work now 👍
