### ISSUE TITLE
[ENHANCEMENT] Add a win state display

### ISSUE THREAD

**Issue by HurleybirdJr** [spsandwichman/consolitaire#2]
## Description
Add a **`YOU WIN`** or similar win / completion state that displays
below the decks for when the user has all 4 suit stacks filled.

## Concept Diagram
[![HIGHLIGHTED IN - GREEN](https://img.shields.io/badge/HIGHLIGHTED_IN-YELLOW-FFCC00?style=for-the-badge)](https://)

![image](https://user-images.githubusercontent.com/45840763/236645632-9b946608-6d6f-4756-a0f0-b181ec489d41.png)

**Comment by HurleybirdJr** [comment]
[YOU_WIN.txt](https://github.com/spsandwichman/consolitaire/files/11413351/YOU_WIN.txt)

**Comment by spsandwichman** [comment]
should be there now :D
