### ISSUE TITLE
[BUG] Visual bug for invalid move over stock cards

### ISSUE THREAD

**Issue by HurleybirdJr** [spsandwichman/consolitaire#3]
## Description
There is a visual bug that makes it possible to appear that placing a currently held card into 
the stock indicator slot is possible despite not being possible to actually place the card there.

## Screenshot
![image](https://user-images.githubusercontent.com/45840763/236650295-8e637745-ab05-4390-8836-c858eac549f6.png)

**Comment by spsandwichman** [comment]
should be good now
