### ISSUE TITLE
[BUG] Cards can clip into text and out of bounds

### ISSUE THREAD

**Issue by HurleybirdJr** [spsandwichman/consolitaire#6]
## Description
There is a visual bug that causes stacked cards to clip into the bottom text and the bounds of the terminal window. 
This becomes especially extreme and apparent when large stacks are moved other other large stacks of cards.

### Possible Fix?
Whether this is an elegant fix or not, it could be worth investigating. Perhaps have it so the window expands sufficiently
for existing stacked cards to not clip. Additionally, when handling cards after picking them up, expand the window for all 
the cards to fit over the biggest stack and then resume the original required window size once the cards have been placed.

## Screenshot
![image](https://user-images.githubusercontent.com/45840763/236651525-681ee572-d6f4-46c0-88c5-1eba816cc961.png)

**Comment by spsandwichman** [comment]
unfortunately, the program can't force the terminal window to expand, but ill look into making the "window too small" warning trigger when something like this happens.

**Comment by spsandwichman** [comment]
should be fixed in the next release
