### ISSUE TITLE
[BUG + CRASH] Possible to pull multiple cards from stack and make illegal moves

### ISSUE THREAD

**Issue by HurleybirdJr** [spsandwichman/consolitaire#7]
## Description
When you hover over more than one card, drawing a card from the stack retains the previous card hover amount instead
of reverting to one card. This causes crashes with fatal index errors if the hover amount is greater than 1 / 2 cards in the 
stack that are shown.

Additionally, if you take from the stack with an overflowing outline greater than 1 card and no crash occurs, the amount of 
cards the outline previously represented is then taken from the stack and can be placed illegally if the top card in the held stack
would be allowed to be placed if it were solo. This then creates impossible card stacks that behave like a normal stack would until
the stack is altered in some way, then card placement rules still apply.

### Bug Diagram:
I've illustrated below a possible visual implementation of what this could look like (not strictly required). 
![image](https://user-images.githubusercontent.com/45840763/236716592-483fda93-4643-49a5-a386-c01ad032f608.png)

#### If the card selector amount is greater than the stack cards, it causes a fatal index error.
![image](https://user-images.githubusercontent.com/45840763/236714463-81b10375-4882-4443-9aab-9168b540c378.png)
![image](https://user-images.githubusercontent.com/45840763/236714632-3fc87a7c-a15f-4e8c-8aff-b32f35644ea9.png)

**Comment by spsandwichman** [comment]
should be fixed now
